ottofeller/templates

src/nextjs/__tests__/index.ts
src/nextjs/index.ts
yarn.lock

This PR solves an issue with the file being reported be `npm run lint` command after a fresh nextjs project bootstrap. The optional line with global.css import is amended at the file start as the easiest way, but thus the file does not comply with prettier config. The problem is resolved at the final stage of a project synthesis.

Add postSynthesize formatting for the _app.tsx file

---

src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/index.ts

The folder is added by default in extendGitignore function and therefore does not need to be added manually.

PLA-222 Remove idea folder from nextjs gitignore

---

.eslintrc.json
.projenrc.ts
src/apollo-server/codegen-config.ts
src/apollo-server/index.ts
src/cdk/index.ts
src/common/codegen/codegen-config-yaml.ts
src/common/codegen/types/CodegenConfig.ts
src/common/codegen/types/ConfiguredOutput.ts
src/common/files/AssetFile.ts
src/common/git/husky.ts
src/nextjs/codegen-config.ts
src/nextjs/index.ts
src/nextjs/jest.ts
src/nextjs/setup-ui-packages.ts

PLa-226 Remove `import/no-relative-parent-imports` rule from the templates repo

---

src/common/github/jobs/job.ts

Closes PLA-226.
The import has leaked from another PR so need to remove it here.

PLA-226 Remove no-relative-parent-imports rule from job.ts

---

.eslintrc.json
.projenrc.ts
package-lock.json
package.json
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/apollo-server/__tests__/index.ts
src/cdk/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/index.ts
src/common/files/__tests__/index.ts
src/common/lint/configs/eslint-config-quality.ts
src/common/vscode-settings/vscode-settings.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/__tests__/index.ts

The rule is added to the project as well as all the templates. "assertionStyle": "never" restricts the use of type assertions. Together with eslint-comments/require-description rule it makes all assertions require an explanation of why it is needed.
Closes PLA-225.

PLA-225 Add consistent-type-assertions rule

---

.projen/deps.json
package-lock.json
package.json
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/lint/add-linters.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/assets/tailwind-config.js
src/nextjs/setup-ui-packages.ts

After update to eslint-plugin-tailwindcss@3.12.1 no custom parser for the TS config is needed.
Closes PLA-231.

PLA-231 Get rid of intermediary tailwind config

---

src/common/github/__tests__/index.ts
src/common/github/pull-request-test-workflow.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap

Closes PLA-235.
The options is pulled from the project options. As a fallback use minNodeVersion from package.
NOTE: This changes the default behaviour: as the `minNodeVersion` is set `12.22.0` by default, the projects that do not set neither `workflowNodeVersion` nor `minNodeVersion` would have their test workflow updated to use node@12.22.0 (previously it used version `16`).

PLA-235 Add workflowNodeVersion option to PullRequestTest

---

.gitattributes
.gitignore
.husky/check-commit-msg.js
.husky/commit-msg
src/common/git/__tests__/index.ts
src/common/git/assets/check-commit-msg.js
src/common/git/assets/commit-msg
src/common/git/husky.ts

Since grep implementation affects correctness of pattern matching and grep version is not controlled in projects, pattern matching part of the script needs a more stable environment and node.js is a good candidate.
The initial script includes a part sourcing `.husky/_/husky.sh` and thus it is not possible to completely move the entire script to node.js. Hence only the part with pattern matching is run in node.js, while everything else is left as is.
Closes PLA-236.

PLA-236 Switch commit message script to node.js

---

src/common/codegen/__tests__/index.ts
src/common/codegen/codegen-config-yaml.ts

Add methods to handle config, preset and presetConfig properties for each generated path.
Closes PLA-237.

PLA-237 Extend CodegenConfigYaml

---

src/nextjs/__tests__/index.ts
src/nextjs/index.ts

The formatting performed in the postSynthesize hook needs to include project outdir for subprojects (otherwise the files are searched for in the root folder).
For nested projects projenrc exists only for the root project and thus subproject have no need to format one.
Closes PLA-240.

PLA-240 Update array of files formatted post synth

---

.eslintrc.json
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/git/__tests__/index.ts
src/common/github/__tests__/index.ts
src/common/github/jobs/__tests__/index.ts
src/common/lint/__tests__/index.ts
src/common/lint/configs/eslint-config-formatting.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/assets/jest.config.js
src/nextjs/sample-code.ts
src/sst/__tests__/__snapshots__/index.ts.snap

Disallow empty lines between one line let and const variable declarations.
Closes PLA-211.

PLA-211 Extend padding-line rule

---

src/sst/__tests__/__snapshots__/index.ts.snap
src/sst/index.ts

The tasks are used internally by NodePackage and are required for proper projen runs. Fixes an error on an attempt to install dependencies.

Restore install tasks in SST template

---

src/common/git/husky/check-cargo.ts
src/common/git/husky/commit-message.ts

Otherwise with no readonly attribute file is not managed by `projen` after removal and stays in the project even when no synthesis of the file is needed.
Note that originally the readonly attribute was added to allow regular hook installation through `husky`. With the readonly attribute it is not possible, though not deems significant - all additional hooks can be added to a template instead of using husky.
Closes PLA-247.

PLA-247 Restore readonly attributes on the husky scripts

---

src/common/github/jobs/__tests__/index.ts
src/common/github/jobs/setup-node.ts

workingDirectory is meant for use only with run steps and causes errors in parsing workflows when applied to external action such as checkout, setup-node etc.

PLA-258 Remove workingDirectory from workflow steps

---

README.md
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/apollo-server/__tests__/index.ts
src/apollo-server/index.ts
src/cdk/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/index.ts
src/cdk/index.ts
src/common/git/husky/add-husky.ts
src/common/lint/add-linters.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/__tests__/index.ts
src/nextjs/index.ts
src/nextjs/jest.ts
src/playwright/__tests__/index.ts
src/playwright/index.ts
src/sst/__tests__/__snapshots__/index.ts.snap
src/sst/__tests__/index.ts
src/sst/index.ts

Running command through projen task runner made ejection process quite heavy for a developer. Thus we move all our commands into package.json and run them as simple npm scripts. The remaining tasks are needed only for projen runs and can be easily deleted after ejection without hurting project functionality.
Closes PLA-265.

Remove projen tasks and replace them with npm scripts

---

src/cdk/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/index.ts
src/cdk/index.ts

Without the tasks cdk fails on synth command and having the command as a npm script is not enought - a projen task is needed.
Closes PLA-268.

Restore bundle task for cdk template

---

src/playwright/index.ts
src/playwright/sample-code.ts

The `.env.development` file is currently not deletable and in order to stop its generation after deletion we need to hide it behind an option - `sampleCode` seems like the good fit.

Move env file into sample code

---

.projen/deps.json
.projenrc.ts
package-lock.json
package.json

Closes PLA-274.
Without the bundled dep the template fails to bootstrap a new project. Even though the dependency is not used at the initial stage, it is referenced and thus must be resolved.

Add node-fetch as a bundled dep

---

src/common/telemetry/collect-telemetry/__tests__/index.ts
src/common/telemetry/telemetry-workflow.ts

Env vars can't be inserted in the call, thus the variable need to be moved into a proper section and the command only calls the necessary script.

Fix incorrect telemetry call in workflow

---

src/common/telemetry/collect-telemetry/__tests__/index.ts
src/common/telemetry/collect-telemetry/collect-escape-hatches.ts

Without this update the `escapeHatches` object is always non-empty because of its keys are always objects, even when there are no entries found in source code.

Telemetry: remove empty objects from collected escape hatches

---

src/apollo-server/index.ts
src/cdk/index.ts
src/playwright/index.ts
src/sst/index.ts

Without this type extension one cannot set telemetry options in any project but nextjs (unless a `ts-ignore` comment is used).

Add telemetry to options to all projects

---

.github/workflows/projen-drift-check.yml
.projenrc.ts
src/common/github/__tests__/index.ts
src/common/github/projen-drift-check-workflow.ts

Add common source code to projen drift check triggers

---

.projen/tasks.json
.projenrc.ts
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/apollo-server/index.ts
src/cdk/__tests__/__snapshots__/index.ts.snap
src/cdk/index.ts
src/common/lint/__tests__/index.ts
src/common/lint/add-linters.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/index.ts
src/playwright/index.ts
src/sst/__tests__/__snapshots__/index.ts.snap
src/sst/index.ts

With the update the `.projenrc.{ext}` is resolved automatically - the file is added to search patterns only when present, and the extension is resolved from the actual file without manual adjustments.
In addition some of the test of the `addLinters` function were found to be corrupt after the switch from _npm_ scripts to _projen_ tasks. The tests are updated to fit the current logic.
Closes PLA-281.

Automatically detect projenrc file in addLinters function

---

src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/index.ts
src/common/github/rust-test-workflow.ts

Add a denial check for unused deps in rust test workflow

---

src/common/github/__tests__/index.ts

The only statement was erroneously left there. Without the statement 53 test cases are unskipped.

Remove only statement on a rest workflow test

---

cspell.json
src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/index.ts
src/common/github/rust-test-workflow.ts

Closes PLA-292.
In the chosen caching schema:
- CARGO_HOME and target folders are cached in a single step;
- each job has its own cache;
- the caches are updated daily (because of nightly updates to rust).

Use cache for rust test workflow

---

.github/workflows/projen-drift-check.yml
.projenrc.ts
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/index.ts
src/common/github/projen-drift-check-workflow.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/sst/__tests__/__snapshots__/index.ts.snap

The purpose is to be able to catch all manual changes to projen-managed files.
Closes PLA-296.

Run projen drift check on all changes

---

.github/workflows/projen-drift-check.yml
.github/workflows/publish-release.yml
.github/workflows/test.yml
.projen/deps.json
.projenrc.ts
package-lock.json
package.json
src/apollo-server/__tests__/__snapshots__/index.ts.snap
src/cdk/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/__snapshots__/index.ts.snap
src/common/github/__tests__/index.ts
src/common/github/jobs/__tests__/index.ts
src/common/github/jobs/lighthouse-job.ts
src/common/github/jobs/setup-node.ts
src/common/telemetry/collect-telemetry/__tests__/index.ts
src/nextjs/__tests__/__snapshots__/index.ts.snap
src/playwright/github/__tests__/__snapshots__/index.ts.snap
src/playwright/github/__tests__/index.ts
src/sst/__tests__/__snapshots__/index.ts.snap

The GitHub actions in the last vesting have migrated its infrastructure to NodeJS@20. Hence along with the actions update, move the workflows to NodeJS@20 as well.
Closes PLA-298.

Update github actions to latest version

---

.npmignore
.projenrc.ts

The files under consideration are irrelevant for production and hence can be removed from the published package.
- `cspell.josn` is a development config. 
- The `examples` folder contains usage examples and complements the documentation in readme. Even though one might want to look up examples, the `node_modules` is not a usual destination, where a developer seeks this info. All the documentation is still available on GitHub.

Remove cspell config and examples from published files

---

src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/index.ts

Only `nextjs` projects is updated, cause it is the only one that has `minNodeVersion` set and picks that version when `workflowNodeVerison` is undefined. All other projects already use node@20 by default.
Closes PLA-302.

Use node@20 in github workflows within nextjs project

---

src/common/github/projen-drift-check-workflow.ts
src/common/github/rust-test-workflow.ts
src/common/github/typescript-test-workflow.ts
src/playwright/github/playwright-workflow.ts

Thus a project contains less intermediary components.
In addition change return type of all addToProject static methods - now they return the created workflow, if any.
Closes PLA-303.

Make workflows inherit from GithubWorkflow class

---

src/common/tasks/__tests__/index.ts
src/common/tasks/add-task-or-script.ts

The difference between exec and spawn becomes apparent in an ejected project. exec is a shell command and can be rendered as is. spawn is a reference to another task, hence it shall be prefixed with the package manager specific runScriptCommand.
Closes PLA-305.

Fix spawn task handling

---

src/nextjs/__tests__/__snapshots__/index.ts.snap
src/nextjs/index.ts
src/nextjs/jest.ts

Since the command used `spawn` form but was rendered into an `exec` directive, the call to the task resulted in an error. Switching to `spawn` fixes the issue.
Closes PLA-304.

Fix build command in nextjs template

---

.github/workflows/publish-release.yml
.projenrc.ts

Somehow v20 does not bundle dependencies, which causes the package to fail to bootstrap any project
Closes PLA-317.

Fall back to NodeJS@16 in publish action

---

.github/workflows/publish-release.yml
.projen/deps.json
.projenrc.ts
package-lock.json
package.json
src/common/telemetry/collect-telemetry/__tests__/index.ts
src/common/telemetry/collect-telemetry/collect-telemetry.ts

Closes PLA-317.
- Remove `eslint` and `node-fetch` from bundled dependencies.
- Keep `prettier` as bundled dependency and remove it from devDependencies - thus enabling it to be bundled under `npm@9+`.
- Update NodeJS version in publish flow - with the new setup it becomes possible to use v20 for publishing.

Update publish flow: bundled deps and nodes version

---

.husky/commit-msg
.projen/deps.json
package-lock.json
package.json
src/common/git/husky/add-husky.ts
src/common/git/husky/assets/husky-shell-script-template

- Update `husky`;
- remove deprecated code from the hooks;
- make the code in pre-commit hook works with `sh` (the shell used by `husky`).
Closes PLA-329.

Update husky to v9
